// Auto-generated by pnpm run pre:setup for Serverful Execution Mode.
import { resolve } from "node:path";
import { FleetDaemon } from "./serverful/daemon.ts";
import { DEFAULT_FLEET_CONFIG } from "@veolms/fleet-types";

if (typeof process.loadEnvFile === "function") {
  try {
    process.loadEnvFile(resolve(process.cwd(), "apps/fleet-manager/.env.local"));
  } catch {
    try {
      process.loadEnvFile(resolve(process.cwd(), ".env.local"));
    } catch {
      // Fallback
    }
  }
}

async function main(): Promise<void> {
  const dbUrl = process.env.DATABASE_URL;
  if (!dbUrl) {
    console.error("❌ Error: DATABASE_URL is not set in environment or .env.local");
    process.exit(1);
  }

  const port = parseInt(process.env.PORT || "4000", 10);
  const host = process.env.HOST || "127.0.0.1";
  const managerApiUrl = process.env.FLEET_MANAGER_API_URL || `http://${host}:${port}`;

  const daemon = new FleetDaemon({
    host,
    port,
    databaseUrl: dbUrl,
    queueConnectionString: dbUrl,
    coordinationIntervalMs: 2000,
    managerApiUrl,
    fleetConfig: DEFAULT_FLEET_CONFIG,
  });

  await daemon.start();
  console.log(`✅ FleetDaemon running & listening at ${managerApiUrl}`);

  const shutdown = async () => {
    console.log("\n🛑 Shutting down Fleet Manager Daemon...");
    await daemon.stop();
    process.exit(0);
  };

  process.on("SIGINT", shutdown);
  process.on("SIGTERM", shutdown);
}

void main();
