// Auto-generated by pnpm run fleet:pre:setup from @veolms/fleet-plugin-aws.
import { AwsCloudDriver } from "@veolms/fleet-plugin-aws";
import type { CloudDriver } from "@veolms/fleet-types";

export function createConfiguredDriver(): CloudDriver {
  const allowedPool = (
    process.env.AWS_EC2_INSTANCE_TYPES ||
    "c6i.large,c6i.xlarge,c6i.2xlarge,g4dn.xlarge"
  )
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);

  return new AwsCloudDriver({
    region: process.env.AWS_REGION || "us-east-1",
    instanceType: process.env.AWS_EC2_INSTANCE_TYPE || "c6i.xlarge",
    allowedInstanceTypes: allowedPool,
    useSpotInstances: process.env.RUNNER_MODE !== "on_demand",
    tempS3Bucket: process.env.S3_TEMP_BUCKET || "veolms-temp-scratch-bucket",
    prodS3Bucket:
      process.env.S3_PROD_BUCKET || "veolms-production-media-bucket",
    fleetManagerApiUrl:
      process.env.FLEET_MANAGER_API_URL || "http://127.0.0.1:4000",
    databaseUrl: process.env.DATABASE_URL,
    amiId: process.env.AWS_EC2_AMI_ID,
    subnetId: process.env.AWS_SUBNET_ID,
    securityGroupIds: process.env.AWS_SECURITY_GROUP_ID
      ? [process.env.AWS_SECURITY_GROUP_ID]
      : undefined,
    iamInstanceProfileArn: process.env.AWS_IAM_ROLE_ARN,
    spotMaxPrice: process.env.AWS_SPOT_MAX_PRICE,
  });
}
